sonar.projectKey=cbl_cvm-ui-boilerplate_3904f53e-ebb6-4931-801d-5a75ded68cfc
sonar.projectName=cvm-ui-boilerplate
sonar.host.url=https://1942.cbl.world
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
