import type React from 'react';
import { colors } from '../../../../design-system/tokens';

export const launchScanDrawerStyles = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 24,
  },
  headerRow: {
    display: 'flex',
    justifyContent: 'flex-end' as const,
  },
  creditsPill: {
    display: 'inline-flex',
    alignItems: 'center' as const,
    gap: 6,
    padding: '4px 10px',
    borderRadius: 999,
    border: '1px solid #FED7AA',
    background: '#FFFBEB',
    fontSize: 12,
    fontWeight: 500,
    color: '#B45309',
    position: 'relative' as const,
    top: -16,
    right: 10,
  },
  stepperRow: {
    display: 'flex',
    alignItems: 'center' as const,
    gap: 8,
    padding: '8px 0 20px',
    borderBottom: '1px solid #E5E7EB',
  },
  stepItem: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center' as const,
    gap: 8,
  },
  stepCircle: (active: boolean, completed?: boolean) => {
    const base: React.CSSProperties = {
      width: 28,
      height: 28,
      borderRadius: '999px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: 13,
      fontWeight: 600,
    };
    if (completed) {
      return {
        ...base,
        background: '#16A34A',
        color: '#FFFFFF',
      };
    }
    if (active) {
      return {
        ...base,
        background: '#2563EB',
        color: '#FFFFFF',
      };
    }
    return {
      ...base,
      background: '#FFFFFF',
      color: '#9CA3AF',
      border: '1px solid #E5E7EB',
    };
  },
  stepLabel: (active: boolean) => ({
    fontSize: 12,
    fontWeight: active ? 600 : 500,
    color: active ? '#111827' : '#9CA3AF',
  }),
  stepConnector: {
    flex: 1,
    height: 2,
    background: '#E5E7EB',
  },
  contentStack: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 0,
  },
  card: {
    borderRadius: 16,
    border: '1px solid #E5E7EB',
    background: colors.bg.surface.default,
    padding: 20,
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: 500,
    color: '#475467',
    marginBottom: 6,
  },
  fieldLabelRow: {
    display: 'flex',
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    marginBottom: 0,
  },
  autoFilledTag: {
    fontSize: 11,
    color: '#667085',
    display: 'inline-flex',
    alignItems: 'center' as const,
    gap: 4,
  },
  textInput: {
    width: '100%',
    borderRadius: 8,
    border: '1px solid #D0D5DD',
    padding: '9px 12px',
    fontSize: 14,
    color: '#111827',
    background: colors.bg.surface.default,
  },
  helperText: {
    marginTop: 6,
    fontSize: 12,
    color: '#667085',
  },
  complianceGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 12,
    marginTop: 8,
  },
  quarterCard: (selected: boolean) => ({
    borderRadius: 14,
    border: selected ? '1px solid #2563EB' : '1px solid #E5E7EB',
    background: selected ? '#F9FAFF' : colors.bg.surface.default,
    padding: 14,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
    boxShadow: selected ? '0 0 0 1px rgba(37, 99, 235, 0.08)' : 'none',
    cursor: 'pointer',
  }),
  quarterHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    marginBottom: 4,
  },
  quarterTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: '#111827',
  },
  statusPill: (bg: string, color: string) => ({
    padding: '3px 8px',
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 500,
    background: bg,
    color,
    display: 'inline-flex',
    alignItems: 'center' as const,
    gap: 4,
  }),
  quarterDates: {
    fontSize: 12,
    color: '#4B5563',
    textAlign: 'left' as const,
  },
  quarterSub: {
    fontSize: 11,
    color: '#6B7280',
    textAlign: 'left' as const,
  },
  quarterAlert: {
    fontSize: 11,
    color: '#B45309',
    display: 'flex',
    alignItems: 'center' as const,
    gap: 4,
  },
  orangeStrip: {
    marginTop: 12,
    borderRadius: 10,
    border: '1px solid #FDBA74',
    background: '#FFFBEB',
    padding: '8px 10px',
    fontSize: 12,
    color: '#B45309',
  },
  scanModeRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 12,
    marginTop: 8,
  },
  scanModeCard: (selected: boolean) => ({
    borderRadius: 10,
    border: selected ? '1px solid #2563EB' : '1px solid #E5E7EB',
    background: selected ? '#F9FAFF' : colors.bg.surface.default,
    padding: 14,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
  }),
  scanModeCardDisabled: {
    borderRadius: 10,
    border: '1px solid #E5E7EB',
    background: '#F9FAFB',
    padding: 14,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
    opacity: 0.55,
    cursor: 'not-allowed',
  },
  scanModeTitleRow: {
    display: 'flex',
    alignItems: 'center' as const,
    gap: 8,
  },
  scanModeTitle:  {
    fontSize: 13,
    fontWeight: 600,
    color: '#111827',
  },
  scanModeTitleDisabled: {
    fontSize: 13,
    fontWeight: 500,
    color: '#9CA3AF',
  },
  radioIcon: (selected: boolean) => ({
    width: 16,
    height: 16,
    borderRadius: 999,
    border: selected ? '4px solid #2563EB' : '1px solid #D0D5DD',
    boxSizing: 'border-box' as const,
  }),
  radioIconDisabled: {
    width: 16,
    height: 16,
    borderRadius: 999,
    border: '1px solid #E5E7EB',
    boxSizing: 'border-box' as const,
  },
  scanModeDescription: {
    fontSize: 12,
    color: '#4B5563',
    textAlign: 'left' as const,
  },
  scanModeDescriptionDisabled: {
    fontSize: 12,
    color: '#9CA3AF',
    textAlign: 'left' as const,
  },
  findingsStrip: {
    marginTop: 12,
    borderRadius: 10,
    border: '1px solid #FEF0C7',
    background: '#FFFBEB',
    padding: '8px 10px',
    fontSize: 12,
    color: '#B45309',
    display: 'flex',
    alignItems: 'center' as const,
    gap: 6,
  },
  readinessStrip: {
    marginTop: 8,
    borderRadius: 10,
    border: '1px solid #FEF0C7',
    background: '#FFFBEB',
    padding: '8px 10px',
    fontSize: 12,
    color: '#B45309',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
  },
  scheduleWarningBanner: {
    marginTop: 0,
    marginBottom: 16,
    borderRadius: 10,
    border: '1px solid #FDBA74',
    background: '#FFFBEB',
    padding: '10px 12px',
    fontSize: 13,
    color: '#B45309',
    display: 'flex',
    alignItems: 'flex-start' as const,
    gap: 8,
  },
  scheduleGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 16,
    marginBottom: 0,
  },
  scheduleField: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
  },
  scheduleInputWrap: {
    display: 'flex',
    alignItems: 'center',
    border: '1px solid #D0D5DD',
    borderRadius: 8,
    background: colors.bg.surface.default,
    overflow: 'hidden',
    cursor: 'text',
  },
  scheduleInputIcon: {
    padding: '9px 10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#6B7280',
    fontSize: 14,
  },
  scheduleInput: {
    flex: 1,
    border: 'none',
    padding: '9px 12px 9px 0',
    fontSize: 14,
    color: '#111827',
    background: 'transparent',
    minWidth: 0,
  },
  scanWindowSection: {
    marginBottom: 20,
  },
  scanWindowDesc: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 12,
  },
  scanWindowGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 12,
  },
  scanWindowCard: (selected: boolean) => ({
    borderRadius: 10,
    border: selected ? '1px solid #2563EB' : '1px solid #E5E7EB',
    background: selected ? '#F9FAFF' : colors.bg.surface.default,
    padding: 14,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
    cursor: 'pointer',
    boxShadow: selected ? '0 0 0 1px rgba(37, 99, 235, 0.08)' : 'none',
  }),
  scanWindowTitleRow: {
    display: 'flex',
    alignItems: 'center' as const,
    gap: 8,
  },
  scanWindowRecommended: {
    padding: '2px 6px',
    borderRadius: 999,
    background: '#ECFDF3',
    color: '#027A48',
    fontSize: 10,
    fontWeight: 600,
  },
  scanWindowTime: {
    fontSize: 12,
    color: '#4B5563',
    textAlign: 'left' as const,
  },
  configSummaryCard: {
    borderRadius: 16,
    border: '1px solid #E5E7EB',
    background: colors.bg.surface.default,
    padding: 20,
  },
  configSummaryRow: {
    display: 'flex',
    justifyContent: 'space-between' as const,
    alignItems: 'center',
    padding: '8px 0',
    borderBottom: '1px solid #F3F4F6',
    fontSize: 13,
  },
  configSummaryLabel: {
    color: '#6B7280',
    fontWeight: 500,
  },
  configSummaryValue: {
    color: '#111827',
    fontWeight: 500,
    textAlign: 'right' as const,
  },
  configSummaryAssetsHeader: {
    fontSize: 11,
    fontWeight: 600,
    color: '#6B7280',
    letterSpacing: '0.5px',
    marginTop: 12,
    marginBottom: 8,
  },
  configSummaryAssetPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 10px',
    borderRadius: 999,
    border: '1px solid #FDE68A',
    background: '#FFFBEB',
    fontSize: 12,
    fontWeight: 500,
    color: '#B45309',
    marginRight: 8,
    marginBottom: 6,
  },
  stepConnectorDone: {
    flex: 1,
    height: 2,
    background: '#16A34A',
  },
} as const;

