import type { ScanRecord } from '../ScansView';

export const SCANS: ScanRecord[] = [
  {
    id: 'SCN-2026-001',
    projectName: 'Q1 2026 PCI ASV Compliance Scan',
    projectType: 'PCI ASV Scan',
    scanName: 'Q1 Full Compliance Assessment',
    schedule: 'Q1 2026 (Mar 15 - Jun 14)',
    startTime: 'Feb 10, 2026 · 08:30',
    status: 'completed',
    actionLabel: 'Rescan',
  },
  {
    id: 'SCN-2026-002',
    projectName: 'Q1 2026 PCI ASV Compliance Scan',
    projectType: 'PCI ASV Scan',
    scanName: 'Q1 Rescan - Vulnerability Remediation',
    schedule: 'Q1 2026 (Mar 15 - Jun 14)',
    startTime: 'Feb 18, 2026 · 09:15',
    status: 'in-progress',
    progressPercent: 45,
  },
  {
    id: 'SCN-2026-003',
    projectName: 'Quarterly PCI ASV Assessment',
    projectType: 'PCI ASV Scan',
    scanName: 'Q4 2025 Final Compliance Assessment',
    schedule: 'Q4 2025 (Dec 15 - Mar 14)',
    startTime: 'Dec 28, 2025 · 22:05',
    status: 'completed',
    actionLabel: 'Rescan',
  },
  {
    id: 'SCN-2026-004',
    projectName: 'Production Network External Scan',
    projectType: 'External VA Scan',
    scanName: 'Weekly Production Infrastructure Scan',
    schedule: 'Weekly',
    startTime: 'Feb 17, 2026 · 07:00',
    status: 'completed',
    actionLabel: 'Rescan',
  },
  {
    id: 'SCN-2026-005',
    projectName: 'DMZ Network External VA',
    projectType: 'External VA Scan',
    scanName: 'DMZ Monthly Assessment',
    schedule: 'Monthly',
    startTime: 'Mar 1, 2026 · 02:00',
    status: 'scheduled',
  },
  {
    id: 'SCN-2026-006',
    projectName: 'Cloud Infrastructure External Assessment',
    projectType: 'External VA Scan',
    scanName: 'AWS Environment Deep Dive',
    schedule: 'One-time',
    startTime: 'Feb 18, 2026 · 18:45',
    status: 'failed',
    actionLabel: 'Retry Scan',
  },
  {
    id: 'SCN-2026-007',
    projectName: 'Production Network External Scan',
    projectType: 'External VA Scan',
    scanName: 'Quarterly Perimeter Assessment',
    schedule: 'Quarterly',
    startTime: 'Feb 23, 2026 · 23:30',
    status: 'completed',
    actionLabel: 'Rescan',
  },
];

