import { colors, spacing } from '../../design-system/tokens';

export const projectSettingsStyles = {
  container: {
    width: '100%',
  },
  tabs: {
    display: 'flex',
    gap: spacing[6],
    borderBottom: `1px solid ${colors.stroke.neutral.light}`,
    marginBottom: spacing[6],
  },
  tab: (active: boolean) => ({
    padding: `${spacing[4]} ${spacing[8]}`,
    fontSize: '16px',
    fontWeight: '500' as const,
    color: active ? '#111625' : colors.text.neutral.sub,
    background: active ? '#E9F0FE' : 'none',
    border: 'none',
    borderRadius: '8px 8px 0 0',
    borderBottom: active ? `2px solid ${colors.primary[500]}` : '2px solid transparent',
    marginBottom: '-1px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  }),
  section: {
    marginBottom: spacing[6],
    background: colors.bg.surface.default,
    border: `1px solid ${colors.stroke.neutral.light}`,
    borderRadius: '12px',
    padding: spacing[6],
    width: '100%',
    maxWidth: '800px',
  },
  sectionTitle: {
    fontSize: '16px',
    fontWeight: '600' as const,
    color: colors.text.neutral.main,
    margin: 0,
    textAlign: 'left' as const,
  },
  sectionSubtitle: {
    fontSize: '14px',
    color: colors.text.neutral.sub,
    marginTop: spacing[1],
    textAlign: 'left' as const,
  },
  formRow: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: spacing[2],
  },
  label: {
    fontSize: '14px',
    fontWeight: '500' as const,
    color: colors.text.neutral.main,
    marginBottom: spacing[2],
    textAlign: 'left' as const,
  },
  teamHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing[5],
  },
  searchWrapper: {
    width: '320px',
  },
  table: {
    width: '100%',
    background: colors.bg.surface.default,
    borderRadius: '12px',
    border: `1px solid ${colors.stroke.neutral.light}`,
    overflow: 'hidden',
  },
  tableHeader: {
    display: 'grid',
    gridTemplateColumns: '300px 1fr 180px 180px 40px',
    gap: spacing[4],
    padding: `${spacing[3]} ${spacing[6]}`,
    background: colors.bg.surface.default,
    borderBottom: `1px solid ${colors.stroke.neutral.light}`,
    fontSize: '12px',
    fontWeight: '500' as const,
    color: colors.text.neutral.soft,
    textAlign: 'left' as const,
  },
  tableRow: (isLast: boolean) => ({
    display: 'grid',
    gridTemplateColumns: '300px 1fr 180px 180px 40px',
    gap: spacing[4],
    padding: `${spacing[4]} ${spacing[6]}`,
    alignItems: 'center',
    borderBottom: isLast ? 'none' : `1px solid ${colors.stroke.neutral.light}`,
    background: colors.bg.surface.default,
  }),
  roleBadge: (color: string) => ({
    display: 'inline-flex',
    alignItems: 'center',
    padding: '2px 8px',
    borderRadius: '16px',
    fontSize: '12px',
    fontWeight: '500' as const,
    color: color,
    background: `${color}15`,
  }),
  lastActive: {
    fontSize: '14px',
    color: colors.text.neutral.sub,
  },
} as const;
