import type { Role } from './roles';
import { ROLES } from './roles';

// Permission definitions - represent business actions
export const PERMISSIONS = {
  // Client permissions
  CLIENT_MANAGE_PROJECTS: 'CLIENT_MANAGE_PROJECTS',
  CLIENT_VIEW_PROJECTS: 'CLIENT_VIEW_PROJECTS',
  CLIENT_CREATE_PROJECTS: 'CLIENT_CREATE_PROJECTS',
  CLIENT_DELETE_PROJECTS: 'CLIENT_DELETE_PROJECTS',
  CLIENT_BUY_SUBSCRIPTION: 'CLIENT_BUY_SUBSCRIPTION',
  CLIENT_MANAGE_USERS: 'CLIENT_MANAGE_USERS',
  CLIENT_VIEW_REPORTS: 'CLIENT_VIEW_REPORTS',
  
  // Tribal permissions
  TRIBAL_ASSIGN_CONSULTANTS: 'TRIBAL_ASSIGN_CONSULTANTS',
  TRIBAL_VIEW_ALL_PROJECTS: 'TRIBAL_VIEW_ALL_PROJECTS',
  TRIBAL_MANAGE_CONSULTANTS: 'TRIBAL_MANAGE_CONSULTANTS',
  TRIBAL_VIEW_ANALYTICS: 'TRIBAL_VIEW_ANALYTICS',
  
  // Shared permissions
  VIEW_ACTIVITY: 'VIEW_ACTIVITY',
  COMMENT: 'COMMENT',
  UPLOAD_EVIDENCE: 'UPLOAD_EVIDENCE',
  VIEW_COMPLIANCE: 'VIEW_COMPLIANCE',
  EDIT_COMPLIANCE: 'EDIT_COMPLIANCE',
  VIEW_VULNERABILITIES: 'VIEW_VULNERABILITIES',
  MANAGE_VULNERABILITIES: 'MANAGE_VULNERABILITIES',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Permission mappings - which roles have which permissions
const PERMISSION_MAP: Record<Role, Permission[]> = {
  [ROLES.CLIENT_ADMIN]: [
    PERMISSIONS.CLIENT_MANAGE_PROJECTS,
    PERMISSIONS.CLIENT_VIEW_PROJECTS,
    PERMISSIONS.CLIENT_CREATE_PROJECTS,
    PERMISSIONS.CLIENT_DELETE_PROJECTS,
    PERMISSIONS.CLIENT_BUY_SUBSCRIPTION,
    PERMISSIONS.CLIENT_MANAGE_USERS,
    PERMISSIONS.CLIENT_VIEW_REPORTS,
    PERMISSIONS.VIEW_ACTIVITY,
    PERMISSIONS.COMMENT,
    PERMISSIONS.UPLOAD_EVIDENCE,
    PERMISSIONS.VIEW_COMPLIANCE,
    PERMISSIONS.EDIT_COMPLIANCE,
    PERMISSIONS.VIEW_VULNERABILITIES,
    PERMISSIONS.MANAGE_VULNERABILITIES,
  ],
  
  [ROLES.CLIENT_PROJECT_MANAGER]: [
    PERMISSIONS.CLIENT_VIEW_PROJECTS,
    PERMISSIONS.CLIENT_CREATE_PROJECTS,
    PERMISSIONS.CLIENT_VIEW_REPORTS,
    PERMISSIONS.VIEW_ACTIVITY,
    PERMISSIONS.COMMENT,
    PERMISSIONS.UPLOAD_EVIDENCE,
    PERMISSIONS.VIEW_COMPLIANCE,
    PERMISSIONS.EDIT_COMPLIANCE,
    PERMISSIONS.VIEW_VULNERABILITIES,
    PERMISSIONS.MANAGE_VULNERABILITIES,
  ],
  
  [ROLES.CLIENT_PROJECT_USER]: [
    PERMISSIONS.CLIENT_VIEW_PROJECTS,
    PERMISSIONS.VIEW_ACTIVITY,
    PERMISSIONS.COMMENT,
    PERMISSIONS.UPLOAD_EVIDENCE,
    PERMISSIONS.VIEW_COMPLIANCE,
    PERMISSIONS.VIEW_VULNERABILITIES,
  ],
  
  [ROLES.TRIBAL_ADMIN]: [
    PERMISSIONS.TRIBAL_ASSIGN_CONSULTANTS,
    PERMISSIONS.TRIBAL_VIEW_ALL_PROJECTS,
    PERMISSIONS.TRIBAL_MANAGE_CONSULTANTS,
    PERMISSIONS.TRIBAL_VIEW_ANALYTICS,
    PERMISSIONS.VIEW_ACTIVITY,
    PERMISSIONS.COMMENT,
    PERMISSIONS.VIEW_COMPLIANCE,
    PERMISSIONS.VIEW_VULNERABILITIES,
  ],
  
  [ROLES.TRIBAL_CONSULTANT_MANAGER]: [
    PERMISSIONS.TRIBAL_ASSIGN_CONSULTANTS,
    PERMISSIONS.TRIBAL_VIEW_ALL_PROJECTS,
    PERMISSIONS.VIEW_ACTIVITY,
    PERMISSIONS.COMMENT,
    PERMISSIONS.VIEW_COMPLIANCE,
    PERMISSIONS.VIEW_VULNERABILITIES,
  ],
  
  [ROLES.TRIBAL_CONSULTANT_USER]: [
    PERMISSIONS.TRIBAL_VIEW_ALL_PROJECTS,
    PERMISSIONS.VIEW_ACTIVITY,
    PERMISSIONS.COMMENT,
    PERMISSIONS.VIEW_COMPLIANCE,
    PERMISSIONS.VIEW_VULNERABILITIES,
  ],
};

// Single helper function - the ONLY way to check permissions
export const can = (role: Role | null | undefined, permission: Permission): boolean => {
  if (!role) return false;
  return PERMISSION_MAP[role]?.includes(permission) ?? false;
};

// Batch permission check
export const canAny = (role: Role | null | undefined, permissions: Permission[]): boolean => {
  return permissions.some(permission => can(role, permission));
};

// All permissions check
export const canAll = (role: Role | null | undefined, permissions: Permission[]): boolean => {
  return permissions.every(permission => can(role, permission));
};
