import { colors, spacing } from '../../design-system/tokens';

export const projectDetailStyles = {
  projectHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[4],
  },
  projectHeaderLeft: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: spacing[1],
  },
  projectTitle: {
    fontSize: '30px',
    fontWeight: '600' as const,
    color: colors.text.neutral.main,
    margin: 0,
    lineHeight: '38px',
  },
  projectMeta: {
    fontSize: '14px',
    color: colors.text.neutral.sub,
    margin: 0,
  },
  teamSection: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing[3],
  },
  teamMembersContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing[0],
  },
  avatar: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    background: '#E9F0FE',
    color: colors.primary[600],
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '16px',
    fontWeight: '600' as const,
    border: '2px solid white',
    marginLeft: '-8px',
  },
  firstAvatar: {
    marginLeft: 0,
  },
  moreCount: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    background: '#F2F4F7',
    border: '2px solid white',
    marginLeft: '-8px',
    fontSize: '14px',
    fontWeight: '500' as const,
    color: colors.text.neutral.sub,
  },
  card: {
    background: colors.bg.surface.default,
    borderRadius: '16px',
    border: `1px solid ${colors.stroke.neutral.soft}`,
    overflow: 'hidden' as const,
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: `${spacing[5]} ${spacing[6]} ${spacing[4]}`,
    borderBottom: `1px solid ${colors.stroke.neutral.light}`,
  },
  cardHeaderLeft: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: spacing[1],
  },
  cardTitle: {
    color: colors.text.neutral.main,
    fontSize: '18px',
    fontWeight: '600' as const,
    lineHeight: '24px',
    margin: 0,
  },
  cardSubtitle: {
    color: colors.text.neutral.sub,
    fontSize: '14px',
    lineHeight: '20px',
    margin: 0,
  },
  cardBody: {
    padding: `${spacing[5]} ${spacing[6]} ${spacing[6]}`,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: spacing[5],
  },
  detailsRow: {
    display: 'grid',
    gridTemplateColumns: '1.2fr 1.2fr 1.6fr',
    columnGap: spacing[8],
    rowGap: spacing[4],
  },
  detailsColumn: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: spacing[6],
  },
  detailItem: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing[3],
  },
  detailLabelTop: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: '12px',
    color: colors.text.neutral.soft,
    marginBottom: 4,
  },
  pill: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '4px 10px',
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 500 as const,
  },
  detailItemFull: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: spacing[2],
  },
  detailIcon: {
    width: '20px',
    height: '20px',
    color: colors.text.neutral.sub,
    flexShrink: 0,
  },
  detailContent: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing[2],
    flex: 1,
  },
  detailLabel: {
    color: colors.text.neutral.sub,
    fontSize: '14px',
    fontWeight: '400' as const,
    lineHeight: '20px',
    minWidth: '120px',
  },
  detailValue: {
    color: colors.text.neutral.main,
    fontSize: '14px',
    fontWeight: '400' as const,
    lineHeight: '20px',
  },
  descriptionText: {
    color: colors.text.neutral.main,
    fontSize: '14px',
    lineHeight: '20px',
    margin: 0,
  },
  viewAllLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacing[2],
    color: colors.primary[500],
    fontSize: '14px',
    fontWeight: '500',
    lineHeight: '20px',
    cursor: 'pointer',
    background: colors.bg.surface.default,
    border: `1px solid ${colors.primary[500]}`,
    borderRadius: '8px',
    padding: `${spacing[2]} ${spacing[3]}`,
  },
  milestonesTable: {
    width: '100%',
    background: colors.bg.surface.default,
    borderRadius: '16px',
    border: `1px solid ${colors.stroke.neutral.soft}`,
    overflow: 'hidden',
  },
  milestonesTitleRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing[4],
    padding: `${spacing[5]} ${spacing[6]}`,
    background: colors.bg.surface.default,
    borderBottom: `1px solid ${colors.stroke.neutral.light}`,
  },
  milestonesTitleLeft: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: spacing[1],
    textAlign: 'left' as const,
  },
  milestonesTitleText: {
    color: colors.text.neutral.main,
    fontSize: '18px',
    fontWeight: '600' as const,
    lineHeight: '24px',
    margin: 0,
  },
  milestonesTitleSubtitle: {
    color: colors.text.neutral.sub,
    fontSize: '14px',
    lineHeight: '20px',
    margin: 0,
  },
  milestonesTitleRight: {
    flexShrink: 0,
  },
  milestonesColumnHeaders: {
    display: 'grid',
    gridTemplateColumns: '1.5fr 2.5fr 1.4fr 1.6fr 1.1fr',
    gap: spacing[4],
    padding: `${spacing[3]} ${spacing[6]}`,
    background: colors.bg.surface.gray,
    borderBottom: `1px solid ${colors.stroke.neutral.light}`,
    fontSize: '12px',
    fontWeight: '500',
    color: colors.text.neutral.soft,
    textAlign: 'left' as const,
  },
  milestonesHeaderActivity: {
    textAlign: 'left' as const,
  },
  milestonesHeaderDate: {
    textAlign: 'left' as const,
  },
  milestonesHeaderStatus: {
    textAlign: 'left' as const,
  },
  milestoneRow: (isLast: boolean) => ({
    display: 'grid',
    gridTemplateColumns: '1.5fr 2.5fr 1.4fr 1.6fr 1.1fr',
    gap: spacing[4],
    padding: `${spacing[4]} ${spacing[6]}`,
    alignItems: 'center',
    borderBottom: isLast ? 'none' : `1px solid ${colors.stroke.neutral.light}`,
    fontSize: '14px',
    color: colors.text.neutral.main,
    minHeight: '56px',
  }),
  milestoneActivityCell: {
    textAlign: 'left' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  scanHistoryFindingsCell: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    justifyContent: 'flex-start',
  },
  scanHistoryFindingPill: (bg: string, color: string) => ({
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 20,
    padding: '2px 6px',
    borderRadius: 2,
    fontSize: 11,
    fontWeight: 600 as const,
    background: bg,
    color,
  }),
  scanHistoryResultPass: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 12,
    color: '#15803D',
  },
  scanHistoryResultFail: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 12,
    color: '#B91C1C',
  },
  timelineContainer: {
    marginTop: spacing[6],
    borderRadius: 16,
    border: `1px solid ${colors.stroke.neutral.soft}`,
    background: colors.bg.surface.default,
    padding: spacing[5],
  },
  timelineSection: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: spacing[4],
  },
  timelineTitle: {
    fontSize: 18,
    fontWeight: 600 as const,
    color: colors.text.neutral.main,
    margin: 0,
  },
  timelineGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: spacing[4],
  },
  timelineCard: {
    borderRadius: 16,
    border: `1px solid ${colors.stroke.neutral.soft}`,
    background: '#F9FAFB',
    padding: spacing[5],
    height: '170px',
  },
  timelineCardHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[1],
  },
  timelineQuarterLabel: {
    fontSize: 14,
    fontWeight: 600 as const,
    color: colors.text.neutral.main,
  },
  timelineStatusPill: (variant: 'pass' | 'fail' | 'current') => ({
    display: 'inline-flex',
    alignItems: 'center',
    padding: '2px 8px',
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 600 as const,
    border:
      variant === 'pass'
        ? '1px solid #A7F3D0'
        : variant === 'fail'
          ? '1px solid #FCA5A5'
          : '1px solid #BFDBFE',
    background:
      variant === 'pass'
        ? '#ECFDF3'
        : variant === 'fail'
          ? '#FEF2F2'
          : '#EFF6FF',
    color:
      variant === 'pass'
        ? '#166534'
        : variant === 'fail'
          ? '#B91C1C'
          : '#1D4ED8',
  }),
  timelineMeta: {
    fontSize: 12,
    color: colors.text.neutral.sub,
    marginTop: 4,
  },
  timelineMetaRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
    fontSize: 12,
    color: colors.text.neutral.sub,
  },
  timelineMetaValue: {
    fontWeight: 500 as const,
    color: colors.text.neutral.main,
  },
  currentQuarterLayout: {
    display: 'grid',
    gridTemplateColumns: '1.4fr 1.6fr',
    gap: spacing[4],
  },
  currentQuarterContainer: {
    marginTop: spacing[6],
    borderRadius: 16,
    border: `1px solid ${colors.stroke.neutral.soft}`,
    background: colors.bg.surface.default,
    padding: spacing[5],
  },
  currentQuarterCard: {
    borderRadius: 16,
    border: '1px solid #266DF0',
    background: colors.bg.surface.default,
    padding: spacing[5],
    display: 'flex',
    flexDirection: 'column' as const,
    gap: spacing[3],
  },
  currentQuarterHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: 13,
    color: colors.text.neutral.sub,
  },
  currentQuarterStatusRow: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing[2],
    fontSize: 20,
    fontWeight: 600 as const,
    color: '#B91C1C',
  },
  actionRequiredPill: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '4px 10px',
    borderRadius: 999,
    background: '#FEF2F2',
    color: '#B91C1C',
    fontSize: 11,
    fontWeight: 600 as const,
  },
  currentQuarterMetaGrid: {
    display: 'block',
    fontSize: 13,
    color: colors.text.neutral.main,
  },
  currentQuarterMetaLabel: {
    fontSize: 12,
    color: colors.text.neutral.sub,
    marginBottom: 2,
  },
  currentQuarterMetaRow: (withBorder: boolean) => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: withBorder ? spacing[2] : 8,
    marginBottom: withBorder ? spacing[2] : 0,
    borderBottom: withBorder ? `1px solid ${colors.stroke.neutral.soft}` : 'none',
  }),
  currentQuarterMetaValueHighlight: {
    color: '#F04438',
    fontWeight: 500 as const,
  },
  blockersCard: {
    borderRadius: 16,
    border: `1px solid ${colors.stroke.neutral.soft}`,
    background: colors.bg.surface.default,
    padding: spacing[5],
    display: 'flex',
    flexDirection: 'column' as const,
    gap: spacing[3],
  },
  blockersHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  blockersTitle: {
    fontSize: 16,
    fontWeight: 600 as const,
    color: colors.text.neutral.main,
  },
  blockersBadgesRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 12,
  },
  blockersBadgeCritical: {
    padding: '2px 8px',
    borderRadius: 999,
    background: '#FEF2F2',
    color: '#B91C1C',
    fontWeight: 500 as const,
  },
  blockersBadgeMedium: {
    padding: '2px 8px',
    borderRadius: 999,
    background: '#FFF7ED',
    color: '#B45309',
    fontWeight: 500 as const,
  },
  blockersList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 8,
    fontSize: 13,
  },
  blockerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottom: '1px solid #F2F4F7',
    gap: spacing[2],
    paddingBottom: spacing[2],
  },
  blockerLink: {
    color: '#101828',
    fontWeight: 500 as const,
    textDecoration: 'none',
    fontSize: 13,
    // Keeping legacy key to match existing inline styles.
    fontstyle: 'normal' as const,
  },
  blockerLinkText: {
    color: '#667085',
    fontWeight: 400 as const,
    fontSize: 12,
    lineHeight: '20px',
    fontstyle: 'normal' as const,
  },
  blockerSeverityCritical: {
    padding: '2px 8px',
    borderRadius: 999,
    background: '#FEF2F2',
    color: '#B91C1C',
    fontSize: 11,
    fontWeight: 600 as const,
  },
  blockerSeverityHigh: {
    padding: '2px 8px',
    borderRadius: 999,
    background: '#FEF6FF',
    color: '#C026D3',
    fontSize: 11,
    fontWeight: 600 as const,
  },
  blockersFooterLink: {
    marginTop: 105,
    fontSize: 13,
    color: colors.primary[600],
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    cursor: 'pointer',
  },
};

