import type { AssetRecord } from '../ScanComponentsView';

export const ASSETS: AssetRecord[] = [
  {
    id: 'asset-1',
    name: 'prod-web-server-01',
    ipAddress: '203.0.113.45',
    type: 'web-server',
    typeLabel: 'Web Server',
    reachability: 'validated',
    scanStatus: 'completed',
    vulnerabilities: { critical: 2, high: 8, medium: 6, low: 12, info: 8 },
    lastScanned: 'Feb 14, 2026',
    scanId: 'SCN-2026-0302-047',
    actionLabel: 'Review',
  },
  {
    id: 'asset-2',
    name: 'prod-web-server-02',
    ipAddress: '203.0.113.46',
    type: 'web-server',
    typeLabel: 'Web Server',
    reachability: 'validated',
    scanStatus: 'scanning',
    vulnerabilities: { critical: 1, high: 4, medium: 3, low: 8, info: 5 },
    lastScanned: 'In progress',
    scanId: 'SCN-2026-0302-048',
    actionLabel: 'Review',
    scanProgress: 67,
  },
  {
    id: 'asset-3',
    name: 'perimeter-fw-01',
    ipAddress: '203.0.113.1',
    type: 'firewall',
    typeLabel: 'Firewall',
    reachability: 'validated',
    scanStatus: 'completed',
    vulnerabilities: { critical: 0, high: 3, medium: 5, low: 8, info: 2 },
    lastScanned: 'Feb 15, 2026',
    scanId: 'SCN-2026-0302-049',
    actionLabel: 'Review',
  },
  {
    id: 'asset-4',
    name: 'AWS Load Balancer',
    ipAddress: '203.0.113.100',
    type: 'load-balancer',
    typeLabel: 'Load Balancer',
    reachability: 'validated',
    scanStatus: 'never-scanned',
    vulnerabilities: { critical: 0, high: 0, medium: 0, low: 0, info: 0 },
    lastScanned: 'Never',
    actionLabel: 'Validating…',
    actionDisabled: true,
  },
  {
    id: 'asset-5',
    name: 'core-switch-01',
    ipAddress: '203.0.113.80',
    type: 'router',
    typeLabel: 'Router',
    reachability: 'setup-required',
    scanStatus: 'never-scanned',
    vulnerabilities: { critical: 0, high: 0, medium: 0, low: 0, info: 0 },
    lastScanned: 'Never',
    actionLabel: 'Complete Setup',
  },
  {
    id: 'asset-6',
    name: 'payment-gateway-01',
    ipAddress: '203.0.113.56',
    type: 'application-server',
    typeLabel: 'Application Server',
    reachability: 'validated',
    scanStatus: 'queued',
    vulnerabilities: { critical: 3, high: 7, medium: 8, low: 12, info: 15 },
    lastScanned: 'Feb 10, 2026',
    scanId: 'SCN-2026-0302-050',
    actionLabel: 'Review',
  },
  {
    id: 'asset-7',
    name: 'backup-fw-01',
    ipAddress: '203.0.113.52',
    type: 'firewall',
    typeLabel: 'Firewall',
    reachability: 'validated',
    scanStatus: 'completed',
    vulnerabilities: { critical: 0, high: 2, medium: 3, low: 2, info: 3 },
    lastScanned: 'Feb 10, 2026',
    scanId: 'SCN-2026-0302-051',
    actionLabel: 'Review',
  },
  {
    id: 'asset-8',
    name: 'Azure VM Cluster',
    ipAddress: '203.0.113.119',
    type: 'vm-cluster',
    typeLabel: 'Azure VM Cluster',
    reachability: 'failed',
    scanStatus: 'failed',
    vulnerabilities: { critical: 1, high: 3, medium: 4, low: 2, info: 4 },
    lastScanned: 'Feb 12, 2026',
    scanId: 'SCN-2026-0302-052',
    actionLabel: 'Retry Validation',
  },
  {
    id: 'asset-9',
    name: 'edge-router-01',
    ipAddress: '203.0.113.90',
    type: 'router',
    typeLabel: 'Router',
    reachability: 'validated',
    scanStatus: 'queued',
    vulnerabilities: { critical: 0, high: 2, medium: 5, low: 6, info: 6 },
    lastScanned: 'Feb 13, 2026',
    scanId: 'SCN-2026-0302-053',
    actionLabel: 'Review',
  },
  {
    id: 'asset-10',
    name: 'db-server-primary',
    ipAddress: '203.0.113.60',
    type: 'database',
    typeLabel: 'Database Server',
    reachability: 'setup-required',
    scanStatus: 'never-scanned',
    vulnerabilities: { critical: 0, high: 0, medium: 0, low: 0, info: 0 },
    lastScanned: 'Never',
    actionLabel: 'Complete Setup',
  },
];

